# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jake
tagline:          'base'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://JakeBase.github.io

author:
  name:           'Mark Otto'
  url:            http://JakeBase.github.io

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/JakeBase

# Gems
gems: [jekyll-paginate]